import { ASSET_ROWS, INITIAL_PLAN_ROWS } from './mockData';

const importedPhotoRecords = [];

const PHOTO_IMPORT_DEMO_ASSETS = [
  {
    key: 'asset-photo-demo-371',
    inventoryRange: '员工',
    inventoryStatus: '已盘',
    counter: '李磊',
    inventoryDate: '2026-08-24',
    assetTag: '114122102371',
    serialNo: 'PF4M37101',
    category: 'NOTEBOOK',
    subCategory: '笔记本-办公笔记本',
    description: '联想.ThinkPad X1 Carbon',
    quantity: 1,
    originalValue: 8999,
    ebsOriginalValue: 8999,
    netValue: 5399.4,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '员工扫码盘点正常',
    useDescription: '员工办公用机',
    remark: '-',
    owner: '李磊',
    ownerDept: '搜狐媒体.智能媒体研发中心.视频商业.算法',
    ownerLevel: '5',
    city: '北京市',
    building: '搜狐媒体大厦',
    floor: '8F',
    organization: '集团',
    costCenter: '搜狐媒体.智能媒体研发中心',
    enableDate: '2024-03-18',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0002',
    planName: '北京市员工盘点计划',
    planManager: '杨芊',
    supervisor: '韩晓晗',
    executor: '李磊',
    currentOwner: '李磊',
    currentOwnerDept: '搜狐媒体.智能媒体研发中心.视频商业.算法',
    officePhone: '010-6272****',
    email: 'lilei@example.com',
    importMode: '狐小e扫码',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
  {
    key: 'asset-photo-demo-372',
    inventoryRange: '员工',
    inventoryStatus: '未盘',
    counter: '-',
    inventoryDate: '-',
    assetTag: '114122102372',
    serialNo: 'C02Z372A1',
    category: 'NOTEBOOK',
    subCategory: '笔记本-办公笔记本',
    description: '苹果.MacBook Pro 14',
    quantity: 1,
    originalValue: 14999,
    ebsOriginalValue: 14999,
    netValue: 10499.3,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '-',
    useDescription: '视频编辑办公用机',
    remark: '-',
    owner: '韩晓晗',
    ownerDept: '搜狐媒体.内容获取中心.垂直组',
    ownerLevel: '5',
    city: '北京市',
    building: '搜狐媒体大厦',
    floor: '7F',
    organization: '集团',
    costCenter: '搜狐媒体.内容获取中心',
    enableDate: '2025-01-15',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0002',
    planName: '北京市员工盘点计划',
    planManager: '杨芊',
    supervisor: '韩晓晗',
    executor: '韩晓晗',
    currentOwner: '韩晓晗',
    currentOwnerDept: '搜狐媒体.内容获取中心.垂直组',
    officePhone: '010-6272****',
    email: 'hanxiaohan@example.com',
    importMode: '-',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
  {
    key: 'asset-photo-demo-373',
    inventoryRange: '员工',
    inventoryStatus: '代盘',
    counter: '李磊',
    inventoryDate: '2026-08-24',
    assetTag: '114122102373',
    serialNo: '5CG3739X2',
    category: 'NOTEBOOK',
    subCategory: '笔记本-技术笔记本',
    description: '惠普.EliteBook 840 G10',
    quantity: 1,
    originalValue: 8299,
    ebsOriginalValue: 8299,
    netValue: 6224.25,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '由部门同事代盘',
    useDescription: '员工办公用机',
    remark: '-',
    owner: '邓昭明',
    ownerDept: '视频.OTT业务部',
    ownerLevel: '5',
    city: '北京市',
    building: '搜狐媒体大厦',
    floor: '9F',
    organization: '集团',
    costCenter: '视频.OTT业务部',
    enableDate: '2024-09-02',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0002',
    planName: '北京市员工盘点计划',
    planManager: '杨芊',
    supervisor: '韩晓晗',
    executor: '邓昭明',
    currentOwner: '邓昭明',
    currentOwnerDept: '视频.OTT业务部',
    officePhone: '010-6272****',
    email: 'dengzhaoming@example.com',
    importMode: '代盘',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
  {
    key: 'asset-photo-demo-374',
    inventoryRange: '公共',
    inventoryStatus: '已盘',
    counter: 'SOHU01-公共管理员',
    inventoryDate: '2026-08-24',
    assetTag: '114122102374',
    serialNo: 'CN0M374D2',
    category: 'MONITOR',
    subCategory: '显示器-标准显示器',
    description: '戴尔.P2422H 24寸显示器',
    quantity: 1,
    originalValue: 1299,
    ebsOriginalValue: 1299,
    netValue: 649.5,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '公共工位现场盘点正常',
    useDescription: '公共工位显示器',
    remark: '-',
    owner: 'SOHU01-公共管理员',
    ownerDept: '搜狐媒体.行政',
    ownerLevel: '公共',
    city: '北京市',
    building: '搜狐媒体大厦',
    floor: '6F',
    organization: '集团',
    costCenter: '搜狐媒体.行政',
    enableDate: '2023-11-20',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0003',
    planName: '北京市公共资产盘点计划',
    planManager: '杨芊',
    supervisor: '韩晓晗',
    executor: 'SOHU01-公共管理员',
    currentOwner: 'SOHU01-公共管理员',
    currentOwnerDept: '搜狐媒体.行政',
    officePhone: '010-6272****',
    email: 'public@example.com',
    importMode: '扫码枪',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
  {
    key: 'asset-photo-demo-375',
    inventoryRange: '公共',
    inventoryStatus: '未盘',
    counter: '-',
    inventoryDate: '-',
    assetTag: '114122102375',
    serialNo: 'CN0K375P7',
    category: 'MONITOR',
    subCategory: '显示器-标准显示器',
    description: '联想.T24i-30 24寸显示器',
    quantity: 1,
    originalValue: 1099,
    ebsOriginalValue: 1099,
    netValue: 824.25,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '-',
    useDescription: '会议室显示器',
    remark: '-',
    owner: 'SOHU01-公共管理员',
    ownerDept: '搜狐媒体.行政',
    ownerLevel: '公共',
    city: '北京市',
    building: '搜狐媒体大厦',
    floor: '10F',
    organization: '集团',
    costCenter: '搜狐媒体.行政',
    enableDate: '2025-02-13',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0003',
    planName: '北京市公共资产盘点计划',
    planManager: '杨芊',
    supervisor: '韩晓晗',
    executor: 'SOHU01-公共管理员',
    currentOwner: 'SOHU01-公共管理员',
    currentOwnerDept: '搜狐媒体.行政',
    officePhone: '010-6272****',
    email: 'public@example.com',
    importMode: '-',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
  {
    key: 'asset-photo-demo-376',
    inventoryRange: '员工',
    inventoryStatus: '盘亏',
    counter: '张曙光',
    inventoryDate: '2026-08-24',
    assetTag: '114122102376',
    serialNo: 'PC2K376R8',
    category: 'NOTEBOOK',
    subCategory: '笔记本-技术笔记本',
    description: '联想.ThinkPad T14 Gen 4',
    quantity: 1,
    originalValue: 9699,
    ebsOriginalValue: 9699,
    netValue: 7274.25,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '现场未找到设备',
    useDescription: '员工办公用机',
    remark: '-',
    owner: '张曙光',
    ownerDept: '集团总部.MIS部',
    ownerLevel: '5',
    city: '北京市',
    building: '搜狐网络大厦',
    floor: '5F',
    organization: '集团',
    costCenter: '集团总部.MIS部',
    enableDate: '2024-07-08',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0002',
    planName: '北京市员工盘点计划',
    planManager: '杨芊',
    supervisor: '韩晓晗',
    executor: '张曙光',
    currentOwner: '张曙光',
    currentOwnerDept: '集团总部.MIS部',
    officePhone: '010-6272****',
    email: 'zhangshuguang@example.com',
    importMode: '人工确认',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
  {
    key: 'asset-photo-demo-377',
    inventoryRange: '员工',
    inventoryStatus: '已盘',
    counter: '苏伟',
    inventoryDate: '2026-08-23',
    assetTag: '114122102377',
    serialNo: 'PF4N377Q3',
    category: 'NOTEBOOK',
    subCategory: '笔记本-技术笔记本',
    description: '联想.ThinkPad X13 Gen 4',
    quantity: 1,
    originalValue: 7899,
    ebsOriginalValue: 7899,
    netValue: 5924.25,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '员工扫码盘点正常',
    useDescription: '员工办公用机',
    remark: '-',
    owner: '苏伟',
    ownerDept: '搜狐媒体.智能平台.新闻产品中心',
    ownerLevel: '5',
    city: '北京市',
    building: '搜狐媒体大厦',
    floor: '8F',
    organization: '集团',
    costCenter: '搜狐媒体.智能平台',
    enableDate: '2024-05-21',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0002',
    planName: '北京市员工盘点计划',
    planManager: '杨芊',
    supervisor: '韩晓晗',
    executor: '苏伟',
    currentOwner: '苏伟',
    currentOwnerDept: '搜狐媒体.智能平台.新闻产品中心',
    officePhone: '010-6272****',
    email: 'suwei@example.com',
    importMode: '狐小e扫码',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
  {
    key: 'asset-photo-demo-378',
    inventoryRange: '公共',
    inventoryStatus: '代盘',
    counter: 'SOHU01-公共管理员',
    inventoryDate: '2026-08-24',
    assetTag: '114122102378',
    serialNo: 'CN0P378L5',
    category: 'MONITOR',
    subCategory: '显示器-标准显示器',
    description: '戴尔.U2424H 24寸显示器',
    quantity: 1,
    originalValue: 1899,
    ebsOriginalValue: 1899,
    netValue: 1519.2,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '行政管理员代盘',
    useDescription: '公共会议室显示器',
    remark: '-',
    owner: 'SOHU01-公共管理员',
    ownerDept: '搜狐媒体.行政',
    ownerLevel: '公共',
    city: '北京市',
    building: '搜狐媒体大厦',
    floor: '12F',
    organization: '集团',
    costCenter: '搜狐媒体.行政',
    enableDate: '2025-06-30',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0003',
    planName: '北京市公共资产盘点计划',
    planManager: '杨芊',
    supervisor: '韩晓晗',
    executor: 'SOHU01-公共管理员',
    currentOwner: 'SOHU01-公共管理员',
    currentOwnerDept: '搜狐媒体.行政',
    officePhone: '010-6272****',
    email: 'public@example.com',
    importMode: '代盘',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
];

PHOTO_IMPORT_DEMO_ASSETS.forEach((asset) => {
  if (!ASSET_ROWS.some((row) => row.assetTag === asset.assetTag)) ASSET_ROWS.push(asset);
});

const employeePlan = INITIAL_PLAN_ROWS.find((plan) => plan.planNo === 'PLAN-20260818-0002');
if (employeePlan) {
  employeePlan.assetCount = 6;
  employeePlan.countedCount = 3;
  employeePlan.uncountedCount = 3;
}

const publicPlan = INITIAL_PLAN_ROWS.find((plan) => plan.planNo === 'PLAN-20260818-0003');
if (publicPlan) {
  publicPlan.assetCount = 3;
  publicPlan.countedCount = 2;
  publicPlan.uncountedCount = 1;
}

function normalizeBaseName(fileName) {
  const name = String(fileName || '').trim();
  const dotIndex = name.lastIndexOf('.');
  return dotIndex > 0 ? name.slice(0, dotIndex).trim() : name;
}

export function parseInventoryPhotoFileName(fileName) {
  const baseName = normalizeBaseName(fileName);
  const roleMatch = baseName.match(/^(.*?)[_-](整体|部分|局部)$/);
  if (!roleMatch) {
    return { assetTag: baseName, photoType: 'overall' };
  }
  return {
    assetTag: roleMatch[1].trim(),
    photoType: roleMatch[2] === '整体' ? 'overall' : 'partial',
  };
}

export function importInventoryPhotoFiles({ projectNo, files, assets }) {
  const assetMap = new Map((assets || []).map((asset) => [String(asset.assetTag || '').trim(), asset]));
  const matched = [];
  const unmatched = [];
  const invalid = [];

  Array.from(files || []).forEach((file) => {
    if (!file.type?.startsWith('image/')) {
      invalid.push(file.name);
      return;
    }

    const { assetTag, photoType } = parseInventoryPhotoFileName(file.name);
    const asset = assetMap.get(assetTag);
    if (!asset) {
      unmatched.push({ fileName: file.name, assetTag });
      return;
    }

    const existingIndex = importedPhotoRecords.findIndex((record) => (
      record.projectNo === projectNo
      && record.assetTag === assetTag
      && record.photoType === photoType
    ));
    const src = URL.createObjectURL(file);
    const record = {
      key: `${projectNo || 'project'}-${assetTag}-${photoType}`,
      projectNo: projectNo || '',
      assetTag,
      assetKey: asset.key,
      photoType,
      fileName: file.name,
      src,
      importedAt: Date.now(),
    };

    if (existingIndex >= 0) {
      const previous = importedPhotoRecords[existingIndex];
      if (previous?.src?.startsWith('blob:')) URL.revokeObjectURL(previous.src);
      importedPhotoRecords.splice(existingIndex, 1, record);
    } else {
      importedPhotoRecords.push(record);
    }
    matched.push(record);
  });

  return { matched, unmatched, invalid };
}

export function getImportedInventoryPhotos(projectNo) {
  return importedPhotoRecords
    .filter((record) => !projectNo || record.projectNo === projectNo)
    .map((record) => ({ ...record }));
}
