// 资产盘点原型演示数据。字段与规则来自《资产盘点》需求，样例值沿用现有操作轨迹中的可确认数据。

export const PROJECT_INFO = {
  projectNo: 'CP-202608180002',
  projectName: '2026年-年度盘点',
  projectType: '初盘',
  startDate: '2026-08-18',
  endDate: '2026-08-29',
  inventoryType: '年度',
  period: '2026年',
  initialProjectNo: '-',
  samplingMode: '-',
  samplingRatio: '-',
  snapshotTime: '2026-08-18 18:25:30',
  description: '年度资产盘点',
  status: '快照生成',
};

export const PROJECT_ROWS = [
  {
    key: 'CP-202608180001',
    relationGroup: '2026年度盘点链路',
    projectNo: 'CP-202608180001',
    projectType: '初盘',
    projectName: '2026年-年度盘点',
    status: '盘点中',
    startDate: '2026-08-18',
    endDate: '2026-08-31',
    executionCount: 51611,
    assetCount: 103688,
    owner: '系统管理员',
    createdAt: '2026-08-18',
    planStatus: '进入计划',
    imageApproval: true,
  },
  {
    key: 'DCP-202608180001',
    relationGroup: '2026年度盘点链路',
    projectNo: 'DCP-202608180001',
    projectType: '抽盘',
    projectName: '2026年-年度抽盘',
    status: '生成盘点计划',
    startDate: '2026-09-02',
    endDate: '2026-09-10',
    executionCount: 5161,
    assetCount: 51611,
    owner: '系统管理员',
    createdAt: '2026-08-18',
    planStatus: '进入计划',
    imageApproval: true,
  },
  {
    key: 'RCP-202608180001',
    relationGroup: '2026年度盘点链路',
    projectNo: 'RCP-202608180001',
    projectType: '复盘',
    projectName: '2026年-年度复盘',
    status: '暂存',
    startDate: '2026-09-12',
    endDate: '2026-09-20',
    executionCount: 4129,
    assetCount: 51611,
    owner: '系统管理员',
    createdAt: '2026-08-18',
    planStatus: '',
    imageApproval: false,
  },
  {
    key: 'CP-202608170001',
    relationGroup: '2026年8月盘点链路',
    projectNo: 'CP-202608170001',
    projectType: '初盘',
    projectName: '2026年8月-月度盘点',
    status: '暂存',
    startDate: '2026-08-17',
    endDate: '2026-08-20',
    executionCount: 0,
    assetCount: 0,
    owner: '系统管理员',
    createdAt: '2026-08-17',
    planStatus: '',
    imageApproval: false,
  },
  {
    key: 'CP-202603040002',
    relationGroup: '2026年第一季度盘点链路',
    projectNo: 'CP-202603040002',
    projectType: '初盘',
    projectName: '2026年第一季度-季度盘点',
    status: '快照生成',
    startDate: '2026-03-04',
    endDate: '2026-03-27',
    executionCount: 28706,
    assetCount: 55568,
    owner: '系统管理员',
    createdAt: '2026-03-04',
    planStatus: '',
    imageApproval: true,
  },
];

export const INVENTORY_RANGE_METHOD_ROWS = [
  { key: 'warehouse', range: '库房', methods: ['狐小e扫码', '扫码枪'], remark: '' },
  { key: 'public', range: '公共', methods: ['狐小e扫码', '扫码枪'], remark: '' },
  { key: 'machine', range: '机房', methods: ['人工上传盘点结果'], remark: 'NO/MIS同步能力待机房蓝图确认' },
  { key: 'employee', range: '员工', methods: ['狐小e扫码'], remark: '员工盘点支持照片上传' },
];

export const IMAGE_RULE_ROWS = [
  {
    key: 'image-warehouse',
    range: '库房',
    ownerLevel: ['全部'],
    department: ['全部'],
    category: ['全部'],
    assetStatus: ['全部'],
    organization: ['集团'],
    city: ['北京市'],
    building: ['全部'],
    floor: ['全部'],
    percent: 100,
  },
  {
    key: 'image-public',
    range: '公共',
    ownerLevel: ['全部'],
    department: ['全部'],
    category: ['全部'],
    assetStatus: ['全部'],
    organization: ['集团'],
    city: ['北京市'],
    building: ['全部'],
    floor: ['全部'],
    percent: 100,
  },
  {
    key: 'image-machine',
    range: '机房',
    ownerLevel: ['全部'],
    department: ['全部'],
    category: ['SERVER', 'NET EQUIPMENT'],
    assetStatus: ['全部'],
    organization: ['集团'],
    city: ['北京市'],
    building: ['融科资讯中心D座'],
    floor: ['B2'],
    percent: 100,
  },
  {
    key: 'image-employee',
    range: '员工',
    ownerLevel: ['全部'],
    department: ['全部'],
    category: ['全部'],
    assetStatus: ['全部'],
    organization: ['集团'],
    city: ['北京市'],
    building: ['全部'],
    floor: ['全部'],
    percent: 100,
  },
];

export const SCOPE_ROWS = [
  {
    key: 'scope-1',
    organization: '集团',
    department: '-',
    assetCategory: 'SERVER、NOTEBOOK',
    assetStatus: '在用、在库',
    warehouse: '-',
    city: '北京市',
    building: '融科资讯中心D座、搜狐媒体大厦',
    floor: 'B2',
    owner: '-',
    ownerLevel: '1、实习生、公共',
    enableFrom: '2020-01-01',
    enableTo: '2026-06-30',
  },
];

export const ASSET_ROWS = [
  {
    key: 'asset-1',
    inventoryRange: '机房',
    inventoryStatus: '未盘',
    counter: '-',
    inventoryDate: '-',
    assetTag: '3103401532-H',
    serialNo: 'SOHUX128275',
    category: 'SERVER',
    subCategory: '服务器-服务器硬盘',
    description: '其他.HD.146G',
    quantity: 1,
    originalValue: 0,
    ebsOriginalValue: 0,
    netValue: 0,
    useStatus: '在用-使用中',
    noLocation: '默认',
    inventoryNote: '-',
    useDescription: '机房服务器配件',
    remark: '-',
    owner: 'SOHU01-库房管理员',
    ownerDept: '虚拟组织',
    ownerLevel: '1',
    city: '北京市',
    building: '融科资讯中心D座',
    floor: 'B2',
    organization: '集团',
    costCenter: '集团总部.MIS',
    enableDate: '2020-06-01',
    mainAssetTag: '3103401533',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0001',
    planName: '北京市盘点计划',
    planManager: '杨芊',
    supervisor: '王鹏',
    executor: 'SOHU01-库房管理员',
    currentOwner: 'SOHU01-库房管理员',
    currentOwnerDept: '虚拟组织',
    officePhone: '010-6272****',
    email: 'warehouse@example.com',
    importMode: '-',
    noScanAssetTag: '3103401532-H',
    noScanSerialNo: 'SOHUX128275',
    noScanBrand: '其他',
    noScanModel: 'HD.146G',
    noScanLocation: '北京市/融科资讯中心D座/B2',
    noScanDiff: '-',
  },
  {
    key: 'asset-2',
    inventoryRange: '机房',
    inventoryStatus: '已盘',
    counter: '系统管理员',
    inventoryDate: '2026-08-18',
    assetTag: '3103401533',
    serialNo: 'CNG821S3F5',
    category: 'SERVER',
    subCategory: '服务器-服务器主机',
    description: '其他.DL360G5',
    quantity: 1,
    originalValue: 0,
    ebsOriginalValue: 0,
    netValue: 0,
    useStatus: '在用-使用中',
    noLocation: '默认',
    inventoryNote: '现场核对正常',
    useDescription: '机房服务器',
    remark: '-',
    owner: 'SOHU01-库房管理员',
    ownerDept: '虚拟组织',
    ownerLevel: '1',
    city: '北京市',
    building: '融科资讯中心D座',
    floor: 'B2',
    organization: '集团',
    costCenter: '集团总部.MIS',
    enableDate: '2019-03-20',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0001',
    planName: '北京市盘点计划',
    planManager: '杨芊',
    supervisor: '王鹏',
    executor: 'SOHU01-库房管理员',
    currentOwner: 'SOHU01-库房管理员',
    currentOwnerDept: '虚拟组织',
    officePhone: '010-6272****',
    email: 'warehouse@example.com',
    importMode: '扫描枪导入',
    noScanAssetTag: '3103401533',
    noScanSerialNo: 'CNG821S3F5',
    noScanBrand: 'HP',
    noScanModel: 'DL360G5',
    noScanLocation: '北京市/融科资讯中心D座/B2',
    noScanDiff: '-',
  },
  {
    key: 'asset-3',
    inventoryRange: '员工',
    inventoryStatus: '报失',
    counter: '苏伟',
    inventoryDate: '2026-08-18',
    assetTag: '3103201755',
    serialNo: '3GTJGT1',
    category: 'NOTEBOOK',
    subCategory: '笔记本-技术笔记本',
    description: '戴尔.E6220技术型',
    quantity: 1,
    originalValue: 6515,
    ebsOriginalValue: 6515,
    netValue: 0,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '员工反馈设备遗失',
    useDescription: '员工用机',
    remark: '-',
    owner: '苏伟',
    ownerDept: '搜狐媒体.智能平台.新闻产品中心',
    ownerLevel: '5',
    city: '北京市',
    building: '搜狐媒体大厦',
    floor: '8F',
    organization: '集团',
    costCenter: '搜狐媒体.智能平台',
    enableDate: '2022-02-11',
    mainAssetTag: '-',
    executeInventory: true,
    needPhoto: true,
    planNo: 'PLAN-20260818-0002',
    planName: '北京市员工盘点计划',
    planManager: '杨芊',
    supervisor: '韩晓晗',
    executor: '苏伟',
    currentOwner: '苏伟',
    currentOwnerDept: '搜狐媒体.智能平台.新闻产品中心',
    officePhone: '010-6272****',
    email: 'suwei@example.com',
    importMode: 'APP导入',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
  {
    key: 'asset-4',
    inventoryRange: '公共',
    inventoryStatus: '未盘',
    counter: '-',
    inventoryDate: '-',
    assetTag: '3102200966',
    serialNo: 'CNBFC22633',
    category: 'MONITOR',
    subCategory: '显示器-标准显示器',
    description: '戴尔.24寸显示器',
    quantity: 1,
    originalValue: 1200,
    ebsOriginalValue: 1200,
    netValue: 100,
    useStatus: '在用-使用中',
    noLocation: '-',
    inventoryNote: '-',
    useDescription: '公共工位',
    remark: '-',
    owner: 'SOHU01-公共管理员',
    ownerDept: '搜狐媒体.行政',
    ownerLevel: '公共',
    city: '北京市',
    building: '搜狐媒体大厦',
    floor: '6F',
    organization: '集团',
    costCenter: '搜狐媒体.行政',
    enableDate: '2023-04-12',
    mainAssetTag: '-',
    executeInventory: false,
    needPhoto: false,
    planNo: '-',
    planName: '-',
    planManager: '-',
    supervisor: '-',
    executor: '-',
    currentOwner: 'SOHU01-公共管理员',
    currentOwnerDept: '搜狐媒体.行政',
    officePhone: '010-6272****',
    email: 'public@example.com',
    importMode: '-',
    noScanAssetTag: '-',
    noScanSerialNo: '-',
    noScanBrand: '-',
    noScanModel: '-',
    noScanLocation: '-',
    noScanDiff: '-',
  },
];

export const UNINCLUDED_ASSET_ROWS = [
  {
    ...ASSET_ROWS[0],
    key: 'asset-unincluded-1',
    assetTag: '3103401999',
    serialNo: 'NO-SCAN-1999',
    noScanAssetTag: '3103401999',
    noScanSerialNo: 'NO-SCAN-1999',
    noScanDiff: 'NO扫描资产标签号与盘点资产标签号不一致',
    executeInventory: false,
  },
];

export const EMPLOYEE_ROWS = [
  { id: 'CW002506', employeeNo: 'CW002506', employeeName: '李磊', department: '搜狐媒体.智能媒体研发中心.视频商业.算法' },
  { id: 'CW002507', employeeNo: 'CW002507', employeeName: '韩晓晗', department: '搜狐媒体.内容获取中心.垂直组' },
  { id: '111488', employeeNo: '111488', employeeName: '邓昭明', department: '视频.OTT业务部' },
  { id: '111494', employeeNo: '111494', employeeName: '苏伟', department: '搜狐媒体.智能平台.新闻产品中心' },
  { id: '111547', employeeNo: '111547', employeeName: '张曙光', department: '集团总部.MIS部' },
  { id: '111558', employeeNo: '111558', employeeName: '王鹏', department: '集团总部.内部审计部' },
];

export const INITIAL_PLAN_ROWS = [
  {
    key: 'plan-1',
    planNo: 'PLAN-20260818-0001',
    planName: '北京市盘点计划',
    status: '暂存',
    organization: '集团',
    city: '北京市',
    range: '机房',
    assetCount: 2,
    uncountedCount: 1,
    countedCount: 1,
    startDate: '2026-08-18',
    endDate: '2026-08-29',
    manager: '杨芊',
    supervisor: '王鹏',
    executor: 'SOHU01-库房管理员',
    financialSupervisor: '-',
    auditSupervisor: '-',
  },
  {
    key: 'plan-2',
    planNo: 'PLAN-20260818-0002',
    planName: '北京市员工盘点计划',
    status: '暂存',
    organization: '集团',
    city: '北京市',
    range: '员工',
    assetCount: 1,
    uncountedCount: 0,
    countedCount: 1,
    startDate: '2026-08-18',
    endDate: '2026-08-29',
    manager: '杨芊',
    supervisor: '韩晓晗',
    executor: '苏伟',
    financialSupervisor: '-',
    auditSupervisor: '-',
  },
  {
    key: 'plan-3',
    planNo: 'PLAN-20260818-0003',
    planName: '北京市公共资产盘点计划',
    status: '暂存',
    organization: '集团',
    city: '北京市',
    range: '公共',
    assetCount: 1,
    uncountedCount: 1,
    countedCount: 0,
    startDate: '2026-08-18',
    endDate: '2026-08-29',
    manager: '杨芊',
    supervisor: '韩晓晗',
    executor: '李磊',
    financialSupervisor: '-',
    auditSupervisor: '-',
  },
];

export const IMAGE_REVIEW_ROWS = [
  {
    key: 'review-1',
    asset: ASSET_ROWS[1],
    reviewStatus: '待审核',
    decision: '',
  },
  {
    key: 'review-2',
    asset: ASSET_ROWS[2],
    reviewStatus: '审核不通过',
    decision: 'fail',
  },
];

export const PROGRESS_ROWS = [
  {
    key: 'progress-employee',
    range: '员工',
    method: '狐小e扫码',
    startDate: '2026-08-18',
    endDate: '2026-08-31',
    expected: 1595,
    counted: 1260,
    lost: 12,
    uncounted: 323,
    progress: 79.0,
    remark: '-',
  },
  {
    key: 'progress-warehouse',
    range: '库房',
    method: '狐小e扫码、扫码枪',
    startDate: '2026-08-18',
    endDate: '2026-08-31',
    expected: 3448,
    counted: 3010,
    lost: 3,
    uncounted: 435,
    progress: 87.3,
    remark: '-',
  },
  {
    key: 'progress-public',
    range: '公共',
    method: '狐小e扫码、扫码枪',
    startDate: '2026-08-18',
    endDate: '2026-08-31',
    expected: 420,
    counted: 300,
    lost: 1,
    uncounted: 119,
    progress: 71.4,
    remark: '-',
  },
  {
    key: 'progress-machine',
    range: '机房',
    method: '人工上传盘点结果',
    startDate: '2026-08-18',
    endDate: '2026-08-31',
    expected: 51611,
    counted: 42300,
    lost: 0,
    uncounted: 9311,
    progress: 82.0,
    remark: 'NO扫描数据同步待技术确认',
  },
];

export const PROGRESS_DETAIL_ROWS = [
  {
    key: 'detail-1',
    range: '员工',
    organization: '集团',
    department: '搜狐媒体.智能平台',
    city: '北京市',
    expected: 430,
    counted: 360,
    lost: 2,
    uncounted: 68,
    progress: 84.2,
    remainingDays: 13,
    supervisor: '韩晓晗',
    financialSupervisor: '-',
    auditSupervisor: '-',
  },
  {
    key: 'detail-2',
    range: '机房',
    organization: '集团',
    department: '集团总部.MIS部',
    city: '北京市',
    expected: 51611,
    counted: 42300,
    lost: 0,
    uncounted: 9311,
    progress: 82.0,
    remainingDays: 13,
    supervisor: '王鹏',
    financialSupervisor: '-',
    auditSupervisor: '-',
  },
];

export const REPORT_ROWS = [
  {
    key: 'report-server',
    category: '服务器类',
    subCategory: '服务器主机',
    ledgerValue: 10250000.00,
    ledgerCount: 1450,
    inventoryValue: 10190000.00,
    inventoryCount: 1438,
    diffValue: 60000.00,
    diffCount: 12,
    lostValue: 30000.00,
    lostCount: 4,
    uncountedValue: 30000.00,
    uncountedCount: 8,
  },
  {
    key: 'report-notebook',
    category: '电脑类',
    subCategory: '笔记本',
    ledgerValue: 8350000.00,
    ledgerCount: 1260,
    inventoryValue: 8290000.00,
    inventoryCount: 1248,
    diffValue: 60000.00,
    diffCount: 12,
    lostValue: 18000.00,
    lostCount: 3,
    uncountedValue: 42000.00,
    uncountedCount: 9,
  },
];
